// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only

/// <summary>
/// Incremental Roslyn Source Generator that reads settings-reader-skills.json (AdditionalFile)
/// and emits one C# class per skill entry, each inheriting from SettingsReaderSkillBase.
/// Also emits a GeneratedSkillRegistration extension method for DI registration.
/// </summary>

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

#nullable enable

namespace Klacks.Api.SourceGenerators;

[Generator]
public class SettingsReaderSkillGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("settings-reader-skills.json"));

        context.RegisterSourceOutput(jsonFiles, GenerateSkills);
    }

    private static void GenerateSkills(SourceProductionContext context, AdditionalText file)
    {
        var text = file.GetText(context.CancellationToken);
        if (text == null) return;

        var json = text.ToString();

        using var doc = System.Text.Json.JsonDocument.Parse(json);

        if (!doc.RootElement.TryGetProperty("skills", out var skillsElement))
            return;

        var classNames = new List<string>();

        foreach (var skill in skillsElement.EnumerateArray())
        {
            var name = GetString(skill, "name");
            var className = GetString(skill, "className");
            var description = GetString(skill, "description");
            var category = GetString(skill, "category");
            var resultMessage = GetString(skill, "resultMessage");

            if (string.IsNullOrEmpty(className)) continue;

            var permissions = new List<string>();
            if (skill.TryGetProperty("requiredPermissions", out var permsElement))
            {
                foreach (var p in permsElement.EnumerateArray())
                {
                    var val = p.GetString();
                    if (val != null) permissions.Add(val);
                }
            }

            var fields = new List<(string constant, string resultName)>();
            if (skill.TryGetProperty("fields", out var fieldsElement))
            {
                foreach (var f in fieldsElement.EnumerateArray())
                {
                    var constant = GetString(f, "constant");
                    var resultName = GetString(f, "resultName");
                    if (!string.IsNullOrEmpty(constant) && !string.IsNullOrEmpty(resultName))
                        fields.Add((constant, resultName));
                }
            }

            var sensitiveFields = new List<(string constant, string resultName)>();
            if (skill.TryGetProperty("sensitiveFields", out var sensitiveElement))
            {
                foreach (var f in sensitiveElement.EnumerateArray())
                {
                    var constant = GetString(f, "constant");
                    var resultName = GetString(f, "resultName");
                    if (!string.IsNullOrEmpty(constant) && !string.IsNullOrEmpty(resultName))
                        sensitiveFields.Add((constant, resultName));
                }
            }

            var source = GenerateSkillClass(className, name, description, category, resultMessage, permissions, fields, sensitiveFields);
            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
            classNames.Add(className);
        }

        var registrationSource = GenerateRegistration(classNames);
        context.AddSource("GeneratedSkillRegistration.g.cs", SourceText.From(registrationSource, Encoding.UTF8));
    }

    private static string GenerateSkillClass(
        string className,
        string name,
        string description,
        string category,
        string resultMessage,
        List<string> permissions,
        List<(string constant, string resultName)> fields,
        List<(string constant, string resultName)> sensitiveFields)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only");
        sb.AppendLine();
        sb.AppendLine("using Klacks.Api.Application.Constants;");
        sb.AppendLine("using Klacks.Api.Application.Interfaces;");
        sb.AppendLine("using Klacks.Api.Application.Skills.Base;");
        sb.AppendLine("using Klacks.Api.Domain.Attributes;");
        sb.AppendLine("using Klacks.Api.Domain.Constants;");
        sb.AppendLine("using Klacks.Api.Domain.Enums;");
        sb.AppendLine("using Klacks.Api.Domain.Models.Assistant;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Klacks.Api.Application.Skills.Generated;");
        sb.AppendLine();
        sb.AppendLine($"[SkillImplementation(\"{EscapeString(name)}\")]");
        sb.AppendLine($"public class {className} : SettingsReaderSkillBase");
        sb.AppendLine("{");
        sb.AppendLine($"    public {className}(ISettingsRepository settingsRepository)");
        sb.AppendLine("        : base(settingsRepository)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    protected override SettingsSkillConfig SkillConfig { get; } = new SettingsSkillConfig");
        sb.AppendLine("    {");
        sb.AppendLine($"        SkillName = \"{EscapeString(name)}\",");
        sb.AppendLine($"        SkillDescription = \"{EscapeString(description)}\",");
        sb.AppendLine($"        SkillCategory = SkillCategory.{category},");

        sb.Append("        Permissions = new string[] { ");
        var permExprs = new List<string>();
        foreach (var p in permissions)
            permExprs.Add($"Permissions.{p}");
        sb.Append(string.Join(", ", permExprs));
        sb.AppendLine(" },");

        sb.AppendLine($"        ResultMessage = \"{EscapeString(resultMessage)}\",");

        sb.AppendLine("        Fields = new SettingsField[]");
        sb.AppendLine("        {");
        foreach (var field in fields)
        {
            sb.AppendLine($"            new SettingsField({field.constant}, \"{EscapeString(field.resultName)}\"),");
        }
        sb.AppendLine("        },");

        if (sensitiveFields.Count > 0)
        {
            sb.AppendLine("        SensitiveFields = new SensitiveSettingsField[]");
            sb.AppendLine("        {");
            foreach (var field in sensitiveFields)
            {
                sb.AppendLine($"            new SensitiveSettingsField({field.constant}, \"{EscapeString(field.resultName)}\"),");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateRegistration(List<string> classNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Klacks.Api.Application.Skills.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedSkillRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedSettingsSkills(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var className in classNames)
        {
            sb.AppendLine($"        services.AddScoped<{className}>();");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetString(System.Text.Json.JsonElement element, string propertyName)
    {
        if (element.TryGetProperty(propertyName, out var prop))
            return prop.GetString() ?? "";
        return "";
    }

    private static string EscapeString(string? s)
    {
        if (s == null) return "";
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
    }
}
